const Queue = require('./queue');

var q = new Queue();
var val = 100;
q.enqueue(val++);
q.enqueue(val++);
q.enqueue(val++);
q.enqueue(val++);
q.enqueue(val++);
q.enqueue(val++);
console.log(q.dequeue());
console.log(q.dequeue());
console.log(q.dequeue());
console.log(q.dequeue());
console.log(q.dequeue());
console.log(q.dequeue());
console.log(q.dequeue());
console.log(q.dequeue());
console.log(q.dequeue());

q.enqueue(val++);
q.enqueue(val++);
q.enqueue(val++);
q.enqueue(val++);
console.log(q.dequeue(val++));
q.enqueue(val++);
q.enqueue(val++);
console.log(q.dequeue(val++));
q.enqueue(val++);
q.enqueue(val++);
console.log(q.dequeue(val++));
q.dequeue();
q.dequeue();
q.dequeue();
q.dequeue();
q.dequeue();
q.dequeue();
q.dequeue();
q.dequeue();
q.dequeue();
q.dequeue();
q.dequeue();
q.dequeue();
q.dequeue();
q.dequeue();
q.dequeue();
q.dequeue();
q.dequeue();
q.dequeue();
q.dequeue();
q.dequeue();
q.dequeue();
q.dequeue();
q.dequeue();
q.dequeue();
q.dequeue();
q.dequeue();
q.dequeue();
q.dequeue();
q.dequeue();
console.log(q.dequeue());
q.enqueue('Hey!');
console.log(q.size());
console.log(q.dequeue());

